# Generated by Django 5.0.4 on 2024-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthelp', '0002_alter_poste_options_remove_user_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logement',
            name='image',
            field=models.ImageField(blank=True, upload_to='logement_images/'),
        ),
    ]
